### ISSUE TITLE
NPE when running in TE-Console?

### ISSUE THREAD

**Issue by djutras2** [opengeospatial/ets-geotiff11#23]
Can't determine exactly where it's coming from. I think probably an issue with the ctl. Doesn't seem to effect anything.

Stacktrace:
`java.lang.NullPointerException
        at com.occamlab.te.vocabulary.Config.getElementsByTagName(Config.java:189)
        at com.occamlab.te.vocabulary.Config.<init>(Config.java:84)
        at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:88)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
        at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
        at org.testng.TestNG.run(TestNG.java:1037)
        at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:130)
        at org.opengis.cite.geotiff11.TestNGController.doTestRun(TestNGController.java:140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
        at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
        at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
        at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
        at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
        at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
        at net.sf.saxon.Controller.transform(Controller.java:1560)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
        at com.occamlab.te.TECore.executeTemplate(TECore.java:607)
        at com.occamlab.te.TECore.executeXSLFunction(TECore.java:1178)
        at com.occamlab.te.TECore.callFunction(TECore.java:1210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
        at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
        at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
        at net.sf.saxon.expr.Expression.process(Expression.java:461)
        at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
        at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
        at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
        at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
        at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
        at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
        at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
        at net.sf.saxon.Controller.transform(Controller.java:1560)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
        at com.occamlab.te.TECore.executeTemplate(TECore.java:607)
        at com.occamlab.te.TECore.executeTest(TECore.java:818)
        at com.occamlab.te.TECore.execute_test(TECore.java:426)
        at com.occamlab.te.TECore.execute_suite(TECore.java:474)
        at com.occamlab.te.TECore.execute(TECore.java:303)
        at com.occamlab.te.Test.execute(Test.java:324)
        at com.occamlab.te.Test.main(Test.java:83)`

**Comment by cmheazel** [comment]
There are a lot of potential null pointer exceptions in this source code.  I have cleaned up some of them, but there is more work to do.  As long as it doesn't impact the execution of the test, we can live with this one for now.  I'll look into a more permanent resolution for a latter release.
